
cc_library(
    name = "sFoundation",
    srcs = glob([
        "LibINI/src/dictionary.cpp",
        "LibINI/src/iniparser.cpp",
        "LibLinuxOS/src/tekEventsLinux.cpp",
        "LibLinuxOS/src/tekThreadsLinux.cpp",
        "LibLinuxOS/src/version.cpp",
        "LibXML/src/ErrCodeStr.cpp",
        "LibXML/src/pugixml.cpp",
        "sFoundation/src/convererLib.cpp",
        "sFoundation/src/cpmAPI.cpp",
        "sFoundation/src/cpmClassImpl.cpp",
        "sFoundation/src/iscAPI.cpp",
        "sFoundation/src/lnkAccessCommon.cpp",
        "sFoundation/src/meridianNet.cpp",
        "sFoundation/src/netCmdAPI.cpp",
        "sFoundation/src/netCoreFmt.cpp",
        "sFoundation/src/SerialEx.cpp",
        "sFoundation/src/sysClassImpl.cpp",
        "sFoundation/src-linux/lnkAccessLinux.cpp",
        "sFoundation/src-linux/SerialLinux.cpp",
    ]),
    hdrs = glob([
        "inc/inc-private/version.h",
        "inc/inc-private/linux/SerialLinux.h",
        "inc/inc-private/linux/tekEventsLinux.h",
        "inc/inc-private/sFound/converterLib.h",
        "inc/inc-private/sFound/cpmRegs.h",
        "inc/inc-private/sFound/iscRegs.h",
        "inc/inc-private/sFound/lnkAccessAPI.h",
        "inc/inc-private/sFound/lnkAccessCommon.h",
        "inc/inc-private/sFound/meridianHdrs.h",
        "inc/inc-private/sFound/mnDiags.h",
        "inc/inc-private/sFound/mnParamDefs.h",
        "inc/inc-private/sFound/netCmdAPI.h",
        "inc/inc-private/sFound/netCmdPrivate.h",
        "inc/inc-private/sFound/SerialEx.h",
        "inc/inc-private/sFound/sFoundResource.h",
        "inc/inc-private/sFound/tekEvents.h",
        "inc/inc-private/sFound/tekThreads.h",
        "inc/inc-private/sFound/valkeys.h",
        "inc/inc-pub/mnErrors.h",
        "inc/inc-pub/pubCoreRegs.h",
        "inc/inc-pub/pubCpmAdvAPI.h",
        "inc/inc-pub/pubCpmAPI.h",
        "inc/inc-pub/pubCpmCls.h",
        "inc/inc-pub/pubCpmRegs.h",
        "inc/inc-pub/pubDataAcq.h",
        "inc/inc-pub/pubIex.h",
        "inc/inc-pub/pubIQmath.h",
        "inc/inc-pub/pubIscAPI.h",
        "inc/inc-pub/pubIscRegs.h",
        "inc/inc-pub/pubMnNetDef.h",
        "inc/inc-pub/pubMonPort.h",
        "inc/inc-pub/pubMotion.h",
        "inc/inc-pub/pubNetAPI.h",
        "inc/inc-pub/pubPwrReg.h",
        "inc/inc-pub/pubRegFldCommon.h",
        "inc/inc-pub/pubSysCls.h",
        "inc/inc-pub/TeknicDevID.h",
        "inc/inc-pub/tekTypes.h",
        "LibINI/inc/dictionary.h",
        "LibINI/inc/iniparser.h",
        "LibLinuxOS/inc/tekEventsLinux.h",
        "LibXML/inc/ErrCodeStr.hpp",
        "LibXML/inc/pugiconfig.hpp",
        "LibXML/inc/pugixml.hpp",
    ]),
    includes = [
        "inc/inc-pub",
        "LibINI/inc",
        "LibLinuxOS/inc",
        "LibXML/inc",
        "inc/inc-private",
        "inc/inc-private/linux",
        "inc/inc-private/sFound",
    ],
    deps = [],
    data = ["sFoundation/MNuserDriver20.xml"],
    visibility = ["//visibility:public"],
)
